# LATENT SPACE GAME CONFIGURATION

# MODEL CONFIGURATIONS
model_identifier: flux
exp_identifier: latent_space_game
model_id: weights/FLUX.1-schnell
scheduler: null
att_slicing: false
vae_slicing: true
vae_tiling: true
enable_xformers: false
gpu_id: 0
diffusion_steps: 2
guidance_scale: 0.0

# GAME CONFIGURATIONS
output_path: ./game_results
prompt: A beautiful Fantasy Landscape
height: 512  # Increased for better visibility
width: 768   # Increased for better visibility
step_size: 0.5
rand_seed: 0
max_sequence_length: 256

# UI CONFIGURATIONS
ui_colors:
  background_start: [30, 30, 40]
  background_end: [15, 15, 25]
  text_input_bg: [45, 45, 55]
  text_input_border: [80, 80, 100]
  text_color: [220, 220, 230]
  instruction_color: [180, 180, 200]